apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-controller
  labels:
    name: nginx
spec:
  replicas: 2
  selector:
    name: nginx
  template:
    metadata:
      labels: 
       name: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/blacklabelops/nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
