apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-controller
  labels:
    name: nginx
spec:
  replicas: 2
  selector:
    name: nginx
  template:
    metadata:
      labels: 
       name: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/blacklabelops/nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
-----
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels: 
   name: nginx-servcie
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
    nodePort: 30088
  selector:
    name: nginx
